### ISSUE TITLE
0.4.39: pypi source tar ball does not include data

### ISSUE THREAD

**Issue by APN-Pucky** [scikit-hep/scikit-hep-testdata#146]
As a consequence network-sandboxed tests fail even if scikit-hep-testdata is installed from pypi. I'll use the github sources for now, but wanted to let you know about it.

I guess this is intentional since the whole data would be too much to distribute over pypi?

**Comment by ariostas** [comment]
Yeah, this is intentional. I also was confused about this initially, but it is mentioned in the readme.

https://github.com/scikit-hep/scikit-hep-testdata/blob/66b0562fff3b49727a19134725f340b37fd912c0/README.md?plain=1#L41-L45

I think technically it might be possible to distribute on PyPI, but it would be quite inconvenient since it's 350+ MB of data. It only downloads the particular files that it needs from GitHub, so it's a lot more efficient than downloading all data.
