### ISSUE TITLE
Only the latest data files are accessible

### ISSUE THREAD

**Issue by ariostas** [scikit-hep/scikit-hep-testdata#147]
In https://github.com/scikit-hep/uproot5/pull/1115 we noticed that tests seemed to pass even when the newest version of `scikit-hep-testdata` hadn't been deployed to PyPI.

I took a look at the code and found that the data files are always downloaded using these urls:
https://github.com/scikit-hep/scikit-hep-testdata/blob/0fd45bededa40577b795d44e74bb0e7d81387ca5/src/skhep_testdata/local_files.py#L22-L23

This means that if a file gets updated, then it becomes impossible to use the older version by installing an older version of the package, and instead the only option is to manually move the older version of the file into the cache directory. And if a file gets deleted, then it becomes inaccessible.

So with https://github.com/scikit-hep/scikit-hep-testdata/pull/144 I unintentionally made previous RNTuple files inaccessible. In this case it's fine since no one should be using the older RNTuple spec, but there might be cases where files need to be updated, but with the option of using older versions by installing previous versions of this package.

So I think it would be better if the above lines could be replaced with something like
```python
baseurl = f"https://github.com/scikit-hep/scikit-hep-testdata/raw/v{__version__}/src/skhep_testdata/data/" 
zipurl = f"https://github.com/scikit-hep/scikit-hep-testdata/archive/refs/tags/v{__version__}.zip" 
```

and maybe have a fallback in case someone is using an editable version or something like that.

Also, it would be nice if there was a `clear_cache` function.

**Comment by ariostas** [comment]
Okay, I guess this is really a non-issue since it is extremely rare to replace or remove files. I'd be happy to implement `clear_cache` and/or `reload=True` since they're pretty trivial. The checksum idea would be great if files were frequently changing, but it's overkill and would also require more thought about file versioning since older versions would want to get older data so that checksums match.

I'd also be happy just closing this issue and dealing with it manually for RNTuple v1.0.0.

**Comment by jpivarski** [comment]
I don't view this library as something that needs to have all the niceties because it's not user-facing. Since we (developers) know that the cache is in `~/.local/skhepdata`, we can already do `clear_cache` easily by hand. (And even if one couldn't, one would have to search some documentation to _either_ find out where the cache is _or_ find out that there's a `clear_cache` function—one is as good as the other.)

`skhep_testdata.data_path(..., reload: bool = False)` would be a nice convenience for certainty in local testing. This might come up again for RNTuple files, and it's more convenient to have a flag in the function you're actively working with in Python, rather than having to hunt for a particular filename in a separate terminal. You're most likely to be the user of this, so I'll let you decide whether you think it's worth spending the time on it.
