### ISSUE TITLE
Python 3.5 supported?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/scikit-hep-testdata#31]
In setup.cfg,

https://github.com/scikit-hep/scikit-hep-testdata/blob/f22a92fd4d8b238c7838df4fe732e1b983e10e4c/setup.cfg#L27

but when I'm testing it in Python 3.5,

https://github.com/scikit-hep/uproot4/pull/8/checks?check_run_id=683554320#step:8:42

On the other hand, importlib_resources claims to support Python 3.5,

https://importlib-resources.readthedocs.io/en/latest/

so I don't know. This mentions a Python 3.5 bug:

https://importlib-resources.readthedocs.io/en/latest/changelog.html#v1-2-0

but I'm using the latest version.

```
# Name                    Version                   Build  Channel
importlib_resources       1.5.0            py37hc8dfbb8_0    conda-forge
```

It is the case, though, that scikit-hep-testdata is only tested for Pythons 2.7, 3.6, and 3.8. The matrix should probably be expanded if it's claiming to support everything in setup.cfg.

**Comment by henryiii** [comment]
Is it only 3.5 that's having a problem? I think know what this bug is but I thought it was either a backward compat issue added in 1.3 fixed In 1.3.1 (IIRC) and didn't think it was Python specific. However, if they dropped 3.5 support, as many packages are now doing, then maybe we are getting an old version that didn't have trees yet?

**Comment by henryiii** [comment]
Aha, you are trying to use conda-forge with python 3.5. That is not supported and you are getting really old dependencies. 1.0.1 does not have trees, that was added in 1.3 IIRC. This should work fine if you use PyPI.

**Comment by jpivarski** [comment]
I've set up conda for dependencies because I'll eventually need ROOT, and I already need XRootD. If I need to split up where the dependencies come from, ROOT+XRootD from conda, scikit-hep-testdata from pip, then I can't do it automatically from the `requirements*.txt` files anymore; I'll have to do it manually as I used to in Travis. I guess it eventually comes to that.

Incidentally, I have a version of the whole test setup working in Pythons 2.6 and 2.7 that I run on my own machine (because I gave up on 2.7 in GitHub Actions: that's starting to be an uphill battle). So while I'll officially only claim Python 3.5+ (or 3.6+?) support, I'm personally verifying that uproot4 can work on ancient Pythons anyway (apart from extensions like LZ4 and Awkward Arrays). In the 2.6 setup, I've removed all the importlib_resources stuff from scikit-hep-testdata and just find the files with a relative path from `__file__`. As a baseline, that's all that's really needed, in case you want to support ancient Pythons.

Glamour shot:

```
% python2.6 -m pytest tests
============================= test session starts ==============================
platform linux4 -- Python 2.6.9, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: /home/pivarski/irishep/uproot4, inifile: setup.cfg
collected 36 items                                                              

tests/test_0001-source-class.py ..........s.s.s.
tests/test_0006-notify-when-downloaded.py ........sss
tests/test_0007-single-chunk-interface.py ....sss
tests/test_0008-start-interpretation.py ..

===================== 27 passed, 9 skipped in 7.20 seconds =====================
% python2.7 -m pytest tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.2.5, py-1.8.1, pluggy-0.4.0
rootdir: /home/pivarski/irishep/uproot4, inifile: setup.cfg
collected 36 items                                                              

tests/test_0001-source-class.py ..........s.s.s.
tests/test_0006-notify-when-downloaded.py ........sss
tests/test_0007-single-chunk-interface.py ....sss
tests/test_0008-start-interpretation.py ..

===================== 27 passed, 9 skipped in 7.94 seconds =====================
% python -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/pivarski/irishep/uproot4, inifile: setup.cfg
collected 36 items                                                             

tests/test_0001-source-class.py ................                         [ 44%]
tests/test_0006-notify-when-downloaded.py ...........                    [ 75%]
tests/test_0007-single-chunk-interface.py .......                        [ 94%]
tests/test_0008-start-interpretation.py ..                               [100%]

======================== 36 passed in 60.57s (0:01:00) =========================
```

The skipped tests are XRootD, which is only installed in the last because the Python 3.7 setup is conda.

**Comment by henryiii** [comment]
Why not add Python 2.5? How about Python 1.6, while you are at it! Supporting older versions of Python lets people think it's okay to use older Python versions, which it is not. I supported Python 2.6 until a month or so ago in Plumbum, and it was a horrible pain - I constantly had to add hacks to the CI to make sure dependencies kept working. I'm glad this support is secret. ;) But what's in your `python_requires`, then, for uproot? For Plumbum, 1.6.9 is the last version that supports 2.6, and it has a `python_requires` that says so, so if you are on 2.6, Pip will install 1.6.9 instead of the upcoming 1.7.0+. So this has to be formalized in your setup.py.

I'd rather hoped uproot 4 would drop Python 2, and just instruct the 2.7 _and_ 2.6 users to use uproot 3. All their other dependencies are stuck on old versions too, why should they be allowed to upgrade uproot when they can't upgrade anything else? I think, since uproot is somewhat special (run anywhere IO), it probably gets a pass on supporting Python 2.7. And _maybe_ 2.6. But it still bothers me...

**Comment by jpivarski** [comment]
When I was visiting Princeton, I thought you had a different opinion. We were talking about a very pay-as-you-go model in which the core would run everywhere (including your iPad), but when you want features like Awkward Arrays, you need the dependencies of those external libraries. The core uproot4 will only strictly depend on NumPy, and only Awkward brings in the dependency on NumPy 1.13.1 and above. For the core task of interpreting ROOT file bytes as Python objects, there isn't a reason to involve external libraries: it's all just `struct.Struct` and `numpy.frombuffer`.

Python 2.6 is different from earlier Pythons because it is still the default on sites that run Scientific Linux 6. That's why [this issue happened](https://github.com/scikit-hep/uproot/issues/402), for instance. There aren't similar arguments for Python 2.5 or earlier (although I think that's the most fully developed Jython, but physicists don't care about Java). Python 2.4 doesn't have context managers, and I'm designing around them now because many users expected `with` blocks to close files. For remote sessions, I'm having the `__exit__` shut down thread pools and `HTTPSConnections` and `pyxrootd.Files` as well, so that all the resources necessary for physical I/O are strictly managed with the `with` statement.

I'll set up the uproot4 `python_requires` and classifiers to only claim support for 3.5+ or 3.6+, whichever it turns out to be, so the old stuff isn't officially supported. But if some technical reason requires dropping 2.6 or 2.7, I'd like to know _why_ (in the same sense that I know exactly why I don't support 2.4: context managers).

**Comment by henryiii** [comment]
> which the core would run everywhere

My iPad has Python 3.6. But that's why I said I think it gets a pass for supporting Python 2.7. Mostly though, I was talking about heavier *requirements* like binary wheels vs. pure Python. Awkward 1 does not support the Raspberry π sitting behind me, for example - it would be nice if uproot worked there. (I may be able to fix that one case - ARM, but there always may be more).

> I'll set up the uproot4...

I think it's okay to keep 2.7 for now unless you want to drop it. If you do drop it, it greatly simplifies the library (unicode vs. bytes is probably the biggest one, but also chaining exceptions, namespace packages for extensions, etc). If you want to support 2.6, it can be done, but it's asking for pain in setting up the tooling and keeping it up - and it probably should be tested in CI and mentioned in the python_requires if you do support it. There are large improvements to Python packaging that we might not be able to take advantage if you try to support a very old Python version, as well - I think Pip 9 is the last version that supported 2.6, IIRC. And that was before PEP 517/518 builds, manylinux2010, etc.

2.7 added multiple context managers in a single statement (mostly will affect users, I expect). Though mostly I think it's the surrounding infrastructure and the very old compilers required for 2.6.

> default on sites that run Scientific Linux 6.

I think we should (Scikit-HEP) try to make sure users understand that the *system* Python should not be used for analysis, especially on SL6. Even if a user happens to get uproot/etc. working, nothing else will (Pandas. etc), so they will have a horribly crippled system. If we make the minimum clear, users will not spend large amounts of time trying to setup a 2.6 analysis system just to find that something farther down the line does not work and they have to start from scratch.

If enough of our system moves to Python 3 only (PyHF, ZFit I think are already there), then we probably should stop spending time making HEP-specific parts (uproot) work in 2. Awkward and boost-histogram are special, since they are targeting a larger user base. But even for those, we can release a "LTS" final 2 release, and then move on too.

PS: I'm slightly worse on harping about killing Python 2 now that I've had a chance to build a full 3.7 *application* without having to worry about Python 2; it was fantastic.

**Comment by jpivarski** [comment]
You know, I could add a warning if Python 2 is detected (including 2.7). I usually don't like warnings because they're ignorable and often refer to something the user doesn't understand because they happen at some deep level. But this doesn't apply here. Then it would be _possible_ to run Uproot on the bare minimum, for somebody who is working with some weird DAQ situation and isn't in a position to deal with what they ideally should do, but in the development process, at least, the warning would float by, and "You should be using Python 3" is something that I think is understandable at that level.

**Comment by henryiii** [comment]
This is currently supported, and will be until the last scikit-hep project has been updated to 3.6+. Conda killed off < 3.6 some time ago.
